In [1]:
import numpy as np

In [2]:
a = np.loadtxt('Paleotopo_UFH_50km_prec2.csv')

In [3]:
b = np.loadtxt('master_50km_withPresentdayTopo_withPresentdaySedThick.xyz')

In [4]:
a.size

54567

In [5]:
b.size

127323

In [6]:
b[:,4]

array([-2702.45081353, -2934.60850934, -2889.03075866, ...,
       -4809.02030223, -4787.89454428, -4746.90823407])

In [7]:
b.shape

(18189, 7)

In [8]:
a.shape

(18189, 3)

In [9]:
b = b[:,2:5]

In [10]:
b.shape

(18189, 3)

In [11]:
b[1,:]

array([-2.92829574e+06,  4.25665335e+06, -2.93460851e+03])

In [12]:
np.savetxt('master_present.csv',b)

In [13]:
b.size

54567

In [14]:
a.shape, b.shape

((18189, 3), (18189, 3))

In [15]:
c = np.loadtxt('final_elev.txt')

In [16]:
c.shape

(131, 143)

In [21]:
c[:2,1]

array([-4050.75682, -4057.55935])